# Generated by Django 4.0.4 on 2022-05-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ULBForms', '0038_alter_agencyprogressmodel_project_id_and_more'),
        ('TUFIDCOapp', '0170_scrollmodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'Progress Detail Not Entered',
                'verbose_name_plural': 'Progress Details Not Entered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.CreateModel(
            name='SanctionNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'Sanction Detail Not Entered',
                'verbose_name_plural': 'Sanction Details Not Entered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.CreateModel(
            name='ULBProgressIncompleted',
            fields=[
            ],
            options={
                'verbose_name': 'Portal Progress Detail',
                'verbose_name_plural': 'Portal Progress Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencyprogressmodel',),
        ),
        migrations.CreateModel(
            name='ULBSanctionReportError',
            fields=[
            ],
            options={
                'verbose_name': 'Portal Sanction Detail',
                'verbose_name_plural': 'Portal Sanction Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencysanctionmodel',),
        ),
    ]
