# Generated by Django 4.0.3 on 2022-03-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectProgressDetailsReport',
        ),
        migrations.AlterModelOptions(
            name='ulbdetails',
            options={'verbose_name': 'ULB Detail', 'verbose_name_plural': 'ULB Details'},
        ),
    ]
