# Generated by Django 4.0.3 on 2022-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0002_delete_projectprogressdetailsreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='work_awarded_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='With Tax.', max_digits=5, null=True, verbose_name='Word Order Amount'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='work_awarded_amount2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Without Tax', max_digits=5, null=True, verbose_name='Work Order Amount'),
        ),
    ]
