# Generated by Django 4.0.3 on 2022-03-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0003_agencysanctionmodel_work_awarded_amount1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='nc_status',
            field=models.TextField(null=True, verbose_name='Reason for non commencement'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Commenced', 'Not Commenced')], default='Not Commenced', help_text='Select anyone.', max_length=20, null=True),
        ),
    ]
