# Generated by Django 4.0.3 on 2022-03-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0004_agencyprogressmodel_nc_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Expenditure (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='FundRelease',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agency has to send a hard copy of the release request along with photos,etc in the prescribed format', max_digits=5, null=True, verbose_name='Fund Release (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='nc_status',
            field=models.TextField(help_text='Payment made to Contractor', null=True, verbose_name='Reason for non commencement'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Commenced', 'Not Commenced')], default='Not Commenced', help_text='Selecting anyone of the status field is mandatory.', max_length=20, null=True),
        ),
    ]
