# Generated by Django 4.0.3 on 2022-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0005_alter_agencyprogressmodel_expenditure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='FundRelease',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agency has to send a hard copy of the release request along with photos,etc in the prescribed format', max_digits=5, null=True, verbose_name='Fund Release (in lakhs) (Recieved from TUFIDCO)'),
        ),
    ]
