# Generated by Django 4.0.3 on 2022-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0006_alter_agencyprogressmodel_fundrelease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ULBDetails',
        ),
    ]
