# Generated by Django 4.0.3 on 2022-03-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0007_delete_ulbdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='ULBName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ULB Name'),
        ),
    ]
