# Generated by Django 4.0.3 on 2022-03-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0008_agencyprogressmodel_ulbname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='nc_status',
            field=models.TextField(blank=True, help_text='Payment made to Contractor', null=True, verbose_name='Reason for non commencement'),
        ),
    ]
