# Generated by Django 4.0.3 on 2022-03-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0009_alter_agencyprogressmodel_nc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankdetails',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ulbpancard',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
