# Generated by Django 4.0.3 on 2022-03-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0010_agencybankdetails_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment made to Contractor', max_digits=5, null=True, verbose_name='Expenditure (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='nc_status',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for non commencement'),
        ),
    ]
