# Generated by Django 4.0.3 on 2022-03-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0013_alter_agencybankdetails_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='ULBType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ULB Type'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ULBName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ULB Name'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ULBType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ULB Type'),
        ),
    ]
