# Generated by Django 4.0.3 on 2022-03-23 08:09

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0014_agencyprogressmodel_ulbtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': (80.2319139, 13.0376246), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True})),
            ],
        ),
        migrations.AlterModelOptions(
            name='agencybankdetails',
            options={'verbose_name': 'Bank Detail', 'verbose_name_plural': 'Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='agencyprogressmodel',
            options={'verbose_name': 'Progress Detail', 'verbose_name_plural': 'Progress Details'},
        ),
        migrations.AlterModelOptions(
            name='agencysanctionmodel',
            options={'verbose_name': 'Project Sanction Detail', 'verbose_name_plural': 'Project Sanction Details'},
        ),
        migrations.AlterModelOptions(
            name='ulbpancard',
            options={'verbose_name': 'PAN Detail', 'verbose_name_plural': 'PAN Details'},
        ),
        migrations.AlterModelOptions(
            name='ulbprogressincompleted',
            options={'verbose_name': 'Portal Progress Detail', 'verbose_name_plural': 'Portal Progress Details'},
        ),
    ]
