# Generated by Django 4.0.3 on 2022-03-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0015_location_alter_agencybankdetails_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULBSanctionReportError',
            fields=[
            ],
            options={
                'verbose_name': 'Portal Sanction Detail',
                'verbose_name_plural': 'Portal Sanction Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencysanctionmodel',),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='tr_awarded',
            field=models.CharField(blank=True, choices=[('0', 'Yes'), ('1', 'No')], max_length=20, null=True, verbose_name='Tender Sanction Awarded'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='ts_awarded',
            field=models.CharField(blank=True, choices=[('0', 'Yes'), ('1', 'No')], max_length=20, null=True, verbose_name='Technical Sanction Awarded'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='wd_awarded',
            field=models.CharField(blank=True, choices=[('0', 'Yes'), ('1', 'No')], max_length=20, null=True, verbose_name='Work Order Awarded'),
        ),
    ]
