# Generated by Django 4.0.3 on 2022-03-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0018_alter_agencysanctionmodel_work_awarded_amount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='work_awarded_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='With Tax. (Add GST, LWF etc on the above basic cost)', max_digits=5, null=True, verbose_name='Word Order Amount'),
        ),
    ]
