# Generated by Django 4.0.3 on 2022-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0151_delete_location'),
        ('ULBForms', '0019_alter_agencysanctionmodel_work_awarded_amount1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
            ],
            options={
                'verbose_name': 'Project Detail',
                'verbose_name_plural': 'Project Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='work_awarded_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='With Tax. (Add GST, LWF etc on the above basic cost)', max_digits=5, null=True, verbose_name='Work Order Amount'),
        ),
    ]
