# Generated by Django 4.0.3 on 2022-03-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0023_alter_agencysanctionmodel_work_awarded_amount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='valueofworkdone',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Value of Work done (in lakhs)'),
        ),
    ]
