# Generated by Django 4.0.3 on 2022-03-30 17:06

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0030_remove_agencyprogressmodel_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
