# Generated by Django 4.0.3 on 2022-04-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0031_agencyprogressmodel_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankdetails',
            name='ULBType',
            field=models.CharField(max_length=40, null=True, verbose_name='ULB Type'),
        ),
    ]
