# Generated by Django 4.0.3 on 2022-04-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0033_alter_agencybankdetails_ulbtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulbpancard',
            name='ULBType',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ULB Type'),
        ),
    ]
