# Generated by Django 4.0.3 on 2022-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0034_ulbpancard_ulbtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='tr_awarded',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Tender Sanction Awarded'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='ts_awarded',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Technical Sanction Awarded'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='wd_awarded',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Work Order Awarded'),
        ),
    ]
