# Generated by Django 4.0.3 on 2022-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0035_alter_agencysanctionmodel_tr_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ApprovedProjectCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Project Cost'),
        ),
    ]
