# Generated by Django 4.0.4 on 2022-04-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0036_agencysanctionmodel_approvedprojectcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='SchemeShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scheme Share'),
        ),
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='ULBShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ULB Share'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='SchemeShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scheme Share'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ULBShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ULB Share'),
        ),
    ]
