# Generated by Django 4.0.4 on 2022-05-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0038_alter_agencyprogressmodel_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='total_release',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Total Release'),
        ),
    ]
