# Generated by Django 4.0.4 on 2022-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0039_agencyprogressmodel_total_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment made to Contractor', max_digits=5, null=True, verbose_name='Expenditure (in lakhs) (Release to contractors)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='FundRelease',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agency has to send a hard copy of the release request along with photos,etc in the prescribed format', max_digits=5, null=True, verbose_name='Fund Release by TUFIDCO (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='SchemeShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scheme Share (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='ULBShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ULB Share (in lakhs)'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='total_release',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Total Release (in lakhs)'),
        ),
    ]
