# Generated by Django 4.0.4 on 2022-05-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0040_alter_agencyprogressmodel_expenditure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='nc_choices',
            field=models.CharField(choices=[('TS to be obtained', 'TS to be obtained'), ('Tender Stage', 'Tender Stage'), ('Work Order to be Issued', 'Work Order to be Issued'), ('Others', 'Others')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='nc_status',
            field=models.TextField(blank=True, null=True, verbose_name='If Others Specify'),
        ),
    ]
