# Generated by Django 4.0.4 on 2022-05-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0041_agencyprogressmodel_nc_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Commenced', 'Not Commenced')], default='Not Commenced', help_text='Select/ Tick anyone of the above.', max_length=20, null=True),
        ),
    ]
