# Generated by Django 4.0.4 on 2022-05-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0042_alter_agencyprogressmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payment made to Contractor', max_digits=5, null=True, verbose_name='Expenditure (in lakhs)'),
        ),
    ]
