# Generated by Django 4.0.4 on 2022-05-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0044_alter_agencyprogressmodel_nc_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='ApprovedProjectCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Project Cost (in lakhs)'),
        ),
    ]
