# Generated by Django 4.0.4 on 2022-05-31 04:01

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0046_alter_agencyprogressmodel_nc_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankdetails',
            name='IFSC_code',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20, null=True, verbose_name='IFSC Code')),
        ),
        migrations.AlterField(
            model_name='agencybankdetails',
            name='account_number',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=90, null=True, verbose_name='Account Number')),
        ),
        migrations.AlterField(
            model_name='agencybankdetails',
            name='passbookupload',
            field=django_cryptography.fields.encrypt(models.FileField(help_text='Please attach a clear scanned copy front page of the Bank passbook', null=True, upload_to='passbook/', verbose_name='Passbook Front Page Photo')),
        ),
    ]
