# Generated by Django 4.0.4 on 2022-05-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0047_alter_agencybankdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankdetails',
            name='IFSC_code',
            field=models.CharField(max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='agencybankdetails',
            name='account_number',
            field=models.CharField(max_length=90, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='agencybankdetails',
            name='passbookupload',
            field=models.FileField(help_text='Please attach a clear scanned copy front page of the Bank passbook', null=True, upload_to='passbook/', verbose_name='Passbook Front Page Photo'),
        ),
    ]
