# Generated by Django 4.0.4 on 2022-05-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0049_alter_agencybankdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='IFSC_code',
        ),
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='passbookupload',
        ),
    ]
