# Generated by Django 4.0.4 on 2022-05-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0051_agencybankdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='date_and_time',
        ),
    ]
