# Generated by Django 4.0.4 on 2022-05-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0053_agencybankdetails_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulbpancard',
            name='PANno',
        ),
        migrations.RemoveField(
            model_name='ulbpancard',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='ulbpancard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ulbpancard',
            name='panphoto',
        ),
    ]
