# Generated by Django 4.0.4 on 2022-05-31 10:55

from django.db import migrations, models
import django.utils.datetime_safe
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0054_remove_ulbpancard_panno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulbpancard',
            name='PANno',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=60, null=True, verbose_name='PAN Number')),
        ),
        migrations.AddField(
            model_name='ulbpancard',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ulbpancard',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ulbpancard',
            name='panphoto',
            field=django_cryptography.fields.encrypt(models.FileField(help_text='Please Upload a Clear Scanned Copy of PAN', null=True, upload_to='PAN/', verbose_name='PAN Photo')),
        ),
    ]
