# Generated by Django 4.0.4 on 2022-05-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0055_ulbpancard_panno_ulbpancard_date_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulbpancard',
            name='date_and_time',
        ),
    ]
