# Generated by Django 4.0.5 on 2022-06-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0057_ulbpancard_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Sector',
            field=models.CharField(blank=True, choices=[('Lighting System', 'Lighting System'), ('Schools', 'Schools'), ('Play Field', 'Play Field'), ('Name Boards for Streets', 'Name Boards for Streets'), ('Bus Stand', 'Bus Stand'), ('Retaining wall', 'Retaining wall'), ('CC Road', 'CC Road'), ('SWD', 'SWD'), ('Community Hall', 'Community Hall'), ('Parks', 'Parks'), ('Animal Birth Control Centre', 'Animal Birth Control Centre'), ('Metal Beam Crash Barriers', 'Metal Beam Crash Barriers'), ('Paver Block', 'Paver Block'), ('Market', 'Market'), ('BT Road', 'BT Road'), ('Crematorium', 'Crematorium'), ('Roads', 'Roads'), ('Path way for  Different Abled person', 'Path way for  Different Abled person'), ('Culvert', 'Culvert'), ('Water Bodies', 'Water Bodies'), ('Knowledge Centre', 'Knowledge Centre'), ('Water Fountain', 'Water Fountain'), ('Solid Waste Mgt.', 'Solid Waste Mgt.')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Sector',
            field=models.CharField(blank=True, choices=[('Lighting System', 'Lighting System'), ('Schools', 'Schools'), ('Play Field', 'Play Field'), ('Name Boards for Streets', 'Name Boards for Streets'), ('Bus Stand', 'Bus Stand'), ('Retaining wall', 'Retaining wall'), ('CC Road', 'CC Road'), ('SWD', 'SWD'), ('Community Hall', 'Community Hall'), ('Parks', 'Parks'), ('Animal Birth Control Centre', 'Animal Birth Control Centre'), ('Metal Beam Crash Barriers', 'Metal Beam Crash Barriers'), ('Paver Block', 'Paver Block'), ('Market', 'Market'), ('BT Road', 'BT Road'), ('Crematorium', 'Crematorium'), ('Roads', 'Roads'), ('Path way for  Different Abled person', 'Path way for  Different Abled person'), ('Culvert', 'Culvert'), ('Water Bodies', 'Water Bodies'), ('Knowledge Centre', 'Knowledge Centre'), ('Water Fountain', 'Water Fountain'), ('Solid Waste Mgt.', 'Solid Waste Mgt.')], max_length=100, null=True),
        ),
    ]
