# Generated by Django 4.0 on 2021-12-31 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyType', models.CharField(max_length=80, null=True, verbose_name='Agency Type')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('District', models.CharField(max_length=80, null=True, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=80, null=True, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('AgencyName', models.CharField(max_length=80, null=True, verbose_name='Agency Name')),
                ('AgencyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype')),
            ],
        ),
    ]
