# Generated by Django 4.0 on 2021-12-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0004_mastersanctionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='AgencyName',
        ),
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='AgencyType',
        ),
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='District',
        ),
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='Region',
        ),
        migrations.DeleteModel(
            name='AgencyName',
        ),
        migrations.DeleteModel(
            name='AgencyType',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='MasterSanctionForm',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
