# Generated by Django 4.0 on 2021-12-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TUFIDCOapp', '0007_remove_mastersanctionform_agencyname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('Aid', models.IntegerField(primary_key=True, serialize=False)),
                ('Pid', models.IntegerField()),
                ('AgencyName', models.CharField(max_length=80, null=True, verbose_name='Agency Name')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyType', models.CharField(max_length=80, null=True, verbose_name='Agency Type')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('Did', models.IntegerField(primary_key=True, serialize=False)),
                ('Pid', models.IntegerField()),
                ('District', models.CharField(max_length=80, null=True, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=80, null=True, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSanctionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(null=True, verbose_name='S.No.')),
                ('AgencyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname')),
                ('AgencyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.district')),
                ('Region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.region')),
            ],
        ),
        migrations.AddField(
            model_name='agencyname',
            name='AgencyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype'),
        ),
    ]
