# Generated by Django 4.0 on 2021-12-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0012_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
