# Generated by Django 4.0 on 2021-12-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0015_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='AgencyName',
        ),
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='AgencyType',
        ),
        migrations.DeleteModel(
            name='AgencyName',
        ),
        migrations.DeleteModel(
            name='AgencyType',
        ),
    ]
