# Generated by Django 4.0 on 2021-12-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TUFIDCOapp', '0017_delete_grade_remove_mastersanctionform_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyType', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme', models.CharField(max_length=80, null=True, verbose_name='Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=80, null=True, verbose_name='Region')),
                ('AgencyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(max_length=80, null=True, verbose_name='District')),
                ('Region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyName', models.CharField(max_length=80, null=True, verbose_name='AgencyName')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.district')),
            ],
        ),
    ]
