# Generated by Django 4.0 on 2021-12-31 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0018_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSanctionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(null=True, verbose_name='S.No.')),
                ('Sector', models.CharField(max_length=200, null=True, verbose_name='Sector')),
                ('ProjectName', models.CharField(max_length=200, null=True, verbose_name='Name of the Work')),
                ('ProjectCost', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Project Cost')),
                ('ProposedCostByULB', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Proposed Cost by ULB')),
                ('AppraisedCostByTufidco', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Appraised Cost By TUFIDCO')),
                ('SchemeShare', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Scheme Share')),
                ('ULBShare', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='ULB Share')),
                ('GoMeeting', models.IntegerField(blank=True, null=True, verbose_name='GO')),
                ('Date_AS', models.DateField(blank=True, null=True, verbose_name='Date of AS')),
                ('Project_ID', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Project ID')),
                ('AgencyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname')),
                ('AgencyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.district')),
                ('Region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.region')),
                ('Scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme')),
            ],
        ),
    ]
