# Generated by Django 4.0 on 2022-01-01 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TUFIDCOapp', '0020_remove_district_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField(null=True)),
                ('AgencyName', models.CharField(max_length=80, null=True, verbose_name='AgencyName')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyType', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pid', models.IntegerField(null=True)),
                ('District', models.CharField(max_length=80, null=True, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(null=True)),
                ('Pid', models.IntegerField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=80, null=True, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme', models.CharField(max_length=80, null=True, verbose_name='Scheme')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSanctionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(null=True, verbose_name='S.No.')),
                ('Sector', models.CharField(max_length=200, null=True, verbose_name='Sector')),
                ('ProjectName', models.CharField(max_length=200, null=True, verbose_name='Name of the Work')),
                ('ProjectCost', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Project Cost')),
                ('ProposedCostByULB', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Proposed Cost by ULB')),
                ('AppraisedCostByTufidco', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Appraised Cost By TUFIDCO')),
                ('SchemeShare', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Scheme Share')),
                ('ULBShare', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='ULB Share')),
                ('GoMeeting', models.IntegerField(blank=True, null=True, verbose_name='GO')),
                ('Date_AS', models.DateField(blank=True, null=True, verbose_name='Date of AS')),
                ('Project_ID', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Project ID')),
                ('AgencyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname')),
                ('AgencyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.district')),
                ('Region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.region')),
                ('Scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme')),
            ],
        ),
        migrations.AddField(
            model_name='agencyname',
            name='AgencyType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype'),
        ),
    ]
