# Generated by Django 4.0 on 2022-01-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0022_about_body_images_gallery_images_location_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme_faq_questions',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme'),
        ),
    ]
