# Generated by Django 4.0 on 2022-01-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0023_scheme_faq_questions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmainslider',
            name='mainsliders',
            field=models.FileField(null=True, upload_to='mainslider/'),
        ),
    ]
