# Generated by Django 4.0 on 2022-01-03 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0025_alter_mastersanctionform_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyname',
            name='Pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='Pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='AgencyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='AgencyType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='AppraisedCostByTufidco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Appraised Cost By TUFIDCO'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.district'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ProjectCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Project Cost'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Name of the Work'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ProposedCostByULB',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proposed Cost by ULB'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='Region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.region'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='SNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='S.No.'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='Scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='SchemeShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Scheme Share'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='Sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ULBShare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ULB Share'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
