# Generated by Django 4.0 on 2022-01-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0026_alter_agencyname_pid_alter_district_pid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersanctionform',
            name='AppraisedCostByTufidco',
        ),
        migrations.AddField(
            model_name='mastersanctionform',
            name='ApprovedProjectCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Project Cost'),
        ),
    ]
