# Generated by Django 4.0 on 2022-01-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0030_agencybankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankdetails',
            name='passbook_photo',
            field=models.ImageField(null=True, upload_to='passbook/'),
        ),
    ]
