# Generated by Django 4.0 on 2022-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0031_agencybankdetails_passbook_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankdetails',
            name='passbook_photo',
            field=models.FileField(null=True, upload_to='passbook/'),
        ),
    ]
