# Generated by Django 4.0 on 2022-01-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0032_alter_agencybankdetails_passbook_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body_images',
            options={'verbose_name': 'Body Image', 'verbose_name_plural': 'Body Images'},
        ),
        migrations.AlterModelOptions(
            name='mastersanctionform',
            options={'verbose_name': 'Master Sanction Form', 'verbose_name_plural': 'Master Sanction Forms'},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'verbose_name': 'Officer', 'verbose_name_plural': 'Officers'},
        ),
        migrations.AlterModelOptions(
            name='tufidco_info',
            options={'verbose_name': 'TUFIDCO INFO', 'verbose_name_plural': 'TUFIDCO INFOS'},
        ),
    ]
