# Generated by Django 4.0 on 2022-01-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0035_agencysanctionform_physicalprogress_physicalprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalprogress',
            old_name='physical_progress',
            new_name='physicalProgress',
        ),
    ]
