# Generated by Django 4.0 on 2022-01-05 12:52

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0036_rename_physical_progress_physicalprogress_physicalprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionform',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (80.243369, 13.0025217), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True}, null=True),
        ),
    ]
