# Generated by Django 4.0 on 2022-01-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0037_agencysanctionform_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionform',
            name='Latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='agencysanctionform',
            name='Longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
