# Generated by Django 4.0 on 2022-01-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0038_agencysanctionform_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='location',
        ),
    ]
