# Generated by Django 4.0 on 2022-01-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0040_agencysanctionform_projectname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencysanctionform',
            old_name='physicalProgress',
            new_name='physicalProgressPhoto',
        ),
    ]
