# Generated by Django 4.0 on 2022-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0042_remove_physicalprogress_physicalprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysanctionform',
            name='ProjectName',
            field=models.TextField(null=True, verbose_name='Project Name'),
        ),
    ]
