# Generated by Django 4.0 on 2022-01-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0043_alter_agencysanctionform_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionform',
            name='expenditure',
            field=models.CharField(max_length=100, null=True, verbose_name='Expenditure'),
        ),
        migrations.AddField(
            model_name='agencysanctionform',
            name='value',
            field=models.CharField(max_length=100, null=True, verbose_name='Value of Work Done'),
        ),
    ]
