# Generated by Django 4.0 on 2022-01-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0046_agencysanctionform_physicalprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionform',
            name='Sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.mastersanctionform'),
        ),
    ]
