# Generated by Django 4.0 on 2022-01-07 06:41

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0047_agencysanctionform_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True), models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True}),
        ),
    ]
