# Generated by Django 4.0 on 2022-01-07 07:47

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TUFIDCOapp', '0048_alter_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionform',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (0.0, 0.0), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True}),
        ),
    ]
