# Generated by Django 4.0 on 2022-01-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0049_agencysanctionform_user_alter_location_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='user',
        ),
    ]
