# Generated by Django 4.0 on 2022-01-07 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TUFIDCOapp', '0050_remove_agencysanctionform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionform',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
