# Generated by Django 4.0 on 2022-01-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0053_agencybankdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankdetails',
            name='passbook_photo',
            field=models.FileField(null=True, upload_to='passbook/', verbose_name='Passbook Front Page Photo'),
        ),
    ]
