# Generated by Django 4.0 on 2022-01-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0054_alter_agencybankdetails_passbook_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheme_page',
            options={'verbose_name': 'Scheme Page', 'verbose_name_plural': 'Scheme Pages'},
        ),
        migrations.AddField(
            model_name='scheme_page',
            name='pdf1',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='scheme_page',
            name='pdf2',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='scheme_page',
            name='pdf_name',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AlterField(
            model_name='scheme_page',
            name='introduction',
            field=models.TextField(null=True, verbose_name='Introduction'),
        ),
    ]
