# Generated by Django 4.0 on 2022-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0055_alter_scheme_page_options_scheme_page_pdf1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme_page',
            name='pdf2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PDF2 Name'),
        ),
        migrations.AlterField(
            model_name='scheme_page',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pdf Name'),
        ),
    ]
