# Generated by Django 4.0 on 2022-01-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0056_scheme_page_pdf2_name_alter_scheme_page_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme_page',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme'),
        ),
        migrations.AlterField(
            model_name='scheme_page',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
