# Generated by Django 4.0 on 2022-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0057_scheme_page_scheme_alter_scheme_page_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme_page',
            old_name='pdf1',
            new_name='pdf_guidelines',
        ),
        migrations.RenameField(
            model_name='scheme_page',
            old_name='pdf2',
            new_name='ppt1',
        ),
        migrations.RemoveField(
            model_name='scheme_page',
            name='pdf2_name',
        ),
        migrations.RemoveField(
            model_name='scheme_page',
            name='pdf_name',
        ),
        migrations.AddField(
            model_name='scheme_page',
            name='pdf_guidelines2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PDF Name'),
        ),
        migrations.AddField(
            model_name='scheme_page',
            name='ppt_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PPT Name'),
        ),
    ]
