# Generated by Django 4.0 on 2022-01-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0062_alter_agencysanctionform_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysanctionform',
            name='Sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.mastersanctionform'),
        ),
    ]
