# Generated by Django 4.0 on 2022-01-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0063_alter_agencysanctionform_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='ProjectName',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='Project_ID',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='physicalProgress',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='physicalProgressPhoto',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='value',
        ),
    ]
