# Generated by Django 4.0 on 2022-01-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0064_remove_agencysanctionform_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='Sector',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='agencysanctionform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='physicalprogress',
            name='AgencySanctionForm',
        ),
        migrations.DeleteModel(
            name='AgencyBankDetails',
        ),
        migrations.DeleteModel(
            name='AgencySanctionForm',
        ),
        migrations.DeleteModel(
            name='physicalProgress',
        ),
    ]
