# Generated by Django 4.0 on 2022-01-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0066_agencybankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankdetails',
            name='IFSC_code',
            field=models.CharField(max_length=20, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='account_number',
            field=models.IntegerField(null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='bank_name',
            field=models.CharField(max_length=90, null=True, verbose_name='Name of the Bank'),
        ),
        migrations.AddField(
            model_name='agencybankdetails',
            name='branch',
            field=models.CharField(max_length=90, null=True, verbose_name='Branch'),
        ),
    ]
