# Generated by Django 4.0 on 2022-01-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0067_agencybankdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='user',
        ),
    ]
