# Generated by Django 4.0 on 2022-01-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TUFIDCOapp', '0068_remove_agencybankdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencybankdetails',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
