# Generated by Django 4.0 on 2022-01-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TUFIDCOapp', '0070_agencysanctionmodel_alter_agencybankdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
