# Generated by Django 4.0 on 2022-01-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0071_agencysanctionmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='Expenditure',
            field=models.CharField(max_length=50, null=True, verbose_name='Expenditure'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='Longitude',
            field=models.CharField(max_length=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='PhysicalProgress',
            field=models.TextField(null=True, verbose_name='Physical Progress'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ProjectName',
            field=models.TextField(null=True, verbose_name='ProjectName'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Latitude',
            field=models.CharField(max_length=20, null=True, verbose_name='Latitude'),
        ),
    ]
