# Generated by Django 4.0 on 2022-01-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0072_agencysanctionmodel_expenditure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='FundRelease',
            field=models.CharField(max_length=50, null=True, verbose_name='Fund Release'),
        ),
    ]
