# Generated by Django 4.0 on 2022-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0074_alter_agencybankdetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='Scheme',
            field=models.CharField(choices=[('KNMT', 'KNMT'), ('Singara Chennai 2.0', 'Singara Chennai 2.0')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='ProjectName',
            field=models.TextField(blank=True, null=True, verbose_name='ProjectName'),
        ),
    ]
