# Generated by Django 4.0 on 2022-01-15 22:09

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0076_agencysanctionmodel_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (0.0, 0.0), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True}, null=True),
        ),
    ]
