# Generated by Django 4.0 on 2022-01-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0083_agencysanctionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencySanctionModel',
        ),
    ]
