# Generated by Django 4.0 on 2022-01-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0089_agencysanctionmodel_tr_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='wd_awarded',
            field=models.CharField(choices=[('0', 'Yes'), ('0', 'No')], max_length=20, null=True, verbose_name='Work Done Awarded'),
        ),
    ]
