# Generated by Django 4.0 on 2022-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0093_masterreport_alter_mastersanctionform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersanctionform',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Sector',
            field=models.CharField(choices=[('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Market', 'Market'), ('Bus Stand', 'Bus Stand'), ('Park', 'Park'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('SWM', 'SWM'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block'), ('Metal Beam', 'Metal Beam'), ('Culvert', 'Culvert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Sector',
            field=models.CharField(choices=[('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Market', 'Market'), ('Bus Stand', 'Bus Stand'), ('Park', 'Park'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('SWM', 'SWM'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block'), ('Metal Beam', 'Metal Beam'), ('Culvert', 'Culvert')], max_length=100, null=True),
        ),
    ]
