# Generated by Django 4.0 on 2022-01-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0095_alter_masterreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Scheme',
            field=models.CharField(choices=[('KNMT', 'KNMT'), ('Singara Chennai 2.0', 'Singara Chennai 2.0')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Sector',
            field=models.CharField(choices=[('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Market', 'Market'), ('Bus Stand', 'Bus Stand'), ('Park', 'Park'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('SWM', 'SWM'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block'), ('Metal Beam', 'Metal Beam'), ('Culvert', 'Culvert')], max_length=100, null=True),
        ),
    ]
