# Generated by Django 4.0 on 2022-01-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0096_alter_agencysanctionmodel_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery_images',
            name='type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Sector',
            field=models.CharField(choices=[('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Market', 'Market'), ('Park', 'Park'), ('Bus Stand', 'Bus Stand'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('SWM', 'SWM'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block'), ('Metal Beam', 'Metal Beam'), ('Culvert', 'Culvert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Sector',
            field=models.CharField(choices=[('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Market', 'Market'), ('Park', 'Park'), ('Bus Stand', 'Bus Stand'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('SWM', 'SWM'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block'), ('Metal Beam', 'Metal Beam'), ('Culvert', 'Culvert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='AgencyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname', verbose_name='ULB Name'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='AgencyType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype', verbose_name='ULB Type'),
        ),
    ]
