# Generated by Django 4.0 on 2022-01-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0097_gallery_images_type_alter_agencyprogressmodel_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorMasterReport',
            fields=[
            ],
            options={
                'verbose_name': 'Sector wise Report',
                'verbose_name_plural': 'Sectow',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.AlterModelOptions(
            name='agencybankdetails',
            options={'verbose_name': 'ULB Bank Detail', 'verbose_name_plural': 'ULB Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='agencyname',
            options={'verbose_name': 'ULB Name', 'verbose_name_plural': 'ULB Names'},
        ),
        migrations.AlterModelOptions(
            name='agencyprogressmodel',
            options={'verbose_name': 'ULB Progress Detail', 'verbose_name_plural': 'ULB Progress Details'},
        ),
        migrations.AlterModelOptions(
            name='agencysanctionmodel',
            options={'verbose_name': 'ULB Sanction Detail', 'verbose_name_plural': 'ULB Sanction Details'},
        ),
        migrations.AlterModelOptions(
            name='agencytype',
            options={'verbose_name': 'ULB Type', 'verbose_name_plural': 'ULB Types'},
        ),
        migrations.AlterModelOptions(
            name='gallery_images',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='scheme_faq_questions',
            options={'verbose_name': 'Scheme FAQ Question', 'verbose_name_plural': 'Scheme FAQ Questions'},
        ),
        migrations.AlterModelOptions(
            name='tufidco_info',
            options={'verbose_name': 'Tufidco Info', 'verbose_name_plural': 'Tufidco Infos'},
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='ProjectName',
            field=models.TextField(blank=True, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='tsrefno',
            field=models.CharField(max_length=30, null=True, verbose_name='Technical Sanction Reference No.'),
        ),
    ]
