# Generated by Django 4.0 on 2022-01-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TUFIDCOapp', '0098_sectormasterreport_alter_agencybankdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectormasterreport',
            options={'verbose_name': 'Sector wise Report', 'verbose_name_plural': 'Sector wise Reports'},
        ),
        migrations.CreateModel(
            name='ULBPanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PANno', models.CharField(max_length=60, null=True, verbose_name='PAN Number')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Name')),
                ('panphoto', models.FileField(help_text='Please Upload a Clear Scanned Copy of PAN', null=True, upload_to='PAN/', verbose_name='PAN Photo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'ULB PAN Detail',
                'verbose_name_plural': 'ULB PAN Details',
            },
        ),
    ]
