# Generated by Django 4.0 on 2022-01-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0099_alter_sectormasterreport_options_ulbpancard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundReleaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_release', models.DateField(null=True, verbose_name='Date of Release')),
                ('amount', models.TextField(max_length=20, null=True, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Fund Release Detail',
                'verbose_name_plural': 'Fund Release Details',
            },
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'GO Wise Report', 'verbose_name_plural': 'GO Wise Reports'},
        ),
    ]
