# Generated by Django 4.0 on 2022-01-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0100_fundreleasedetails_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundreleasedetails',
            name='masterSanctionForm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.mastersanctionform'),
        ),
    ]
