# Generated by Django 4.0 on 2022-01-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0101_fundreleasedetails_mastersanctionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundreleasedetails',
            name='amount',
            field=models.CharField(max_length=20, null=True, verbose_name='Amount'),
        ),
    ]
