# Generated by Django 4.0 on 2022-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0102_alter_fundreleasedetails_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundreleasedetails',
            name='instruction_report_by_SQM',
            field=models.FileField(null=True, upload_to='SQMreport/'),
        ),
    ]
