# Generated by Django 4.0 on 2022-01-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0103_fundreleasedetails_instruction_report_by_sqm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme_page',
            name='name',
        ),
    ]
