# Generated by Django 4.0 on 2022-01-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0104_remove_scheme_page_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme_page',
            old_name='scheme',
            new_name='Scheme',
        ),
    ]
