# Generated by Django 4.0 on 2022-01-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0105_rename_scheme_scheme_page_scheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme_page',
            old_name='Scheme',
            new_name='scheme',
        ),
        migrations.AddField(
            model_name='scheme_page',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
    ]
