# Generated by Django 4.0 on 2022-01-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0108_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
