# Generated by Django 4.0.2 on 2022-02-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0112_alter_agencyprogressmodel_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='status',
            field=models.CharField(choices=[('--------', '--------'), ('In Progress', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='Sector',
            field=models.CharField(choices=[('Culvert', 'Culvert'), ('Solid Waste Mgt.', 'Solid Waste Mgt.'), ('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Parks', 'Parks'), ('Market', 'Market'), ('Bus Stand', 'Bus Stand'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('Metal Beam Crash Barriers', 'Metal Beam Crash Barriers'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='Sector',
            field=models.CharField(choices=[('Culvert', 'Culvert'), ('Solid Waste Mgt.', 'Solid Waste Mgt.'), ('Community Hall', 'Community Hall'), ('Water Bodies', 'Water Bodies'), ('SWD', 'SWD'), ('Parks', 'Parks'), ('Market', 'Market'), ('Bus Stand', 'Bus Stand'), ('BT Road', 'BT Road'), ('Retaining wall', 'Retaining wall'), ('Knowledge Centre', 'Knowledge Centre'), ('CC Road', 'CC Road'), ('Metal Beam Crash Barriers', 'Metal Beam Crash Barriers'), ('Crematorium', 'Crematorium'), ('Paver Block', 'Paver Block')], max_length=100, null=True),
        ),
    ]
