# Generated by Django 4.0.2 on 2022-02-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0113_agencyprogressmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='status',
            field=models.CharField(choices=[('--------', '--------'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
