# Generated by Django 4.0.2 on 2022-02-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0116_alter_agencyprogressmodel_project_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencysanctionmodel',
            options={'verbose_name': 'ULB Project Sanction Detail', 'verbose_name_plural': 'ULB Project Sanction Details'},
        ),
        migrations.RemoveField(
            model_name='agencysanctionmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ULBName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
