# Generated by Django 4.0.2 on 2022-02-28 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TUFIDCOapp', '0117_alter_agencysanctionmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysanctionmodel',
            name='ULBName',
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
