# Generated by Django 4.0.2 on 2022-03-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0118_remove_agencysanctionmodel_ulbname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencybankdetails',
            name='account_number',
            field=models.CharField(max_length=90, null=True, verbose_name='Account Number'),
        ),
    ]
