# Generated by Django 4.0.3 on 2022-03-01 15:38

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0120_alter_agencyprogressmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (80.2319139, 13.0376246), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': False, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True, 'zoom': 15}, null=True),
        ),
    ]
