# Generated by Django 4.0.3 on 2022-03-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0121_alter_agencyprogressmodel_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterreport',
            options={'verbose_name': 'KNMT Physical & Financial Progress Report', 'verbose_name_plural': 'KNMT Physical & Financial Progress Reports'},
        ),
    ]
