# Generated by Django 4.0.3 on 2022-03-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0122_alter_masterreport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report1', models.FileField(null=True, upload_to='reports/')),
                ('report2', models.FileField(null=True, upload_to='reports/')),
                ('report3', models.FileField(null=True, upload_to='reports/')),
            ],
        ),
    ]
