# Generated by Django 4.0.3 on 2022-03-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0123_latestreports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestreports',
            old_name='report1',
            new_name='report',
        ),
        migrations.RemoveField(
            model_name='latestreports',
            name='report2',
        ),
        migrations.RemoveField(
            model_name='latestreports',
            name='report3',
        ),
    ]
