# Generated by Django 4.0.3 on 2022-03-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0124_rename_report1_latestreports_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestreports',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
