# Generated by Django 4.0.2 on 2022-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0126_alter_agencyprogressmodel_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ApprovedProjectCost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Approved Project Cost'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ProjectCost',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Project Cost'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ProposedCostByULB',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Proposed Cost by ULB'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='SchemeShare',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Scheme Share'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='ULBShare',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='ULB Share'),
        ),
        migrations.AlterField(
            model_name='mastersanctionform',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
