# Generated by Django 4.0.2 on 2022-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0129_alter_agencyprogressmodel_expenditure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='ProjectName',
            field=models.TextField(blank=True, null=True, verbose_name='Project Name'),
        ),
    ]
