# Generated by Django 4.0.3 on 2022-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0130_agencysanctionmodel_projectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictWiseReport',
            fields=[
            ],
            options={
                'verbose_name': 'District Wise Report',
                'verbose_name_plural': 'District Wise Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='wd_awarded',
            field=models.CharField(blank=True, choices=[('0', 'Yes'), ('0', 'No')], max_length=20, null=True, verbose_name='Work Order Awarded'),
        ),
        migrations.AlterField(
            model_name='agencysanctionmodel',
            name='wdawddate',
            field=models.DateField(blank=True, null=True, verbose_name='Work Order Awarded Date'),
        ),
    ]
