# Generated by Django 4.0.3 on 2022-03-06 21:02

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0131_districtwisereport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtwisereport',
            options={'verbose_name': 'DMA District Wise Report', 'verbose_name_plural': 'DMA District Wise Reports'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (80.2319139, 13.0376246), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True, 'zoom': 15}, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': (80.2319139, 13.0376246), 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'Blue', 'navigation_buttons': True, 'readonly': True, 'rotate': True, 'style': 'mapbox://styles/mapbox/satellite-v9', 'track_location_button': True}),
        ),
        migrations.CreateModel(
            name='ULBReleaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_form', models.CharField(max_length=50, null=True, verbose_name='Name of form')),
                ('form', models.FileField(null=True, upload_to='ReleaseRequest/')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme')),
            ],
            options={
                'verbose_name': 'ULB Release Request',
                'verbose_name_plural': 'ULB Release Requests',
            },
        ),
    ]
