# Generated by Django 4.0.3 on 2022-03-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0132_alter_districtwisereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='district',
            name='Longitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
