# Generated by Django 4.0.3 on 2022-03-07 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0133_district_latitude_district_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestreports',
            name='Scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme'),
        ),
        migrations.AlterField(
            model_name='agencybankdetails',
            name='beneficiary_name',
            field=models.CharField(max_length=90, null=True, verbose_name='Name of the ULB'),
        ),
    ]
