# Generated by Django 4.0.3 on 2022-03-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0135_ctpdistrictwisereport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULBProgressIncompleted',
            fields=[
            ],
            options={
                'verbose_name': 'ULB Progress Incompleted',
                'verbose_name_plural': 'ULB Progress Incompleted',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.agencyprogressmodel',),
        ),
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='percentageofworkdone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Percentage'),
        ),
    ]
