# Generated by Django 4.0.3 on 2022-03-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0136_ulbprogressincompleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgressDetailsReport',
            fields=[
            ],
            options={
                'verbose_name': 'Project Progress Details Report',
                'verbose_name_plural': 'Project Progress Details Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.agencyprogressmodel',),
        ),
    ]
