# Generated by Django 4.0.3 on 2022-03-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0137_projectprogressdetailsreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='MasterSanctionForm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TUFIDCOapp.mastersanctionform'),
        ),
    ]
