# Generated by Django 4.0.3 on 2022-03-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0138_agencyprogressmodel_mastersanctionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyprogressmodel',
            name='MasterSanctionForm',
        ),
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='ApprovedProjectCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Approved Project Cost'),
        ),
        migrations.AddField(
            model_name='agencyprogressmodel',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.district'),
        ),
    ]
