# Generated by Django 4.0.3 on 2022-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0139_remove_agencyprogressmodel_mastersanctionform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
    ]
