# Generated by Django 4.0.3 on 2022-03-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0143_alter_agencyprogressmodel_percentageofworkdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='percentageofworkdone',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Percentage of work done'),
        ),
    ]
