# Generated by Django 4.0.3 on 2022-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0144_alter_agencyprogressmodel_percentageofworkdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageCounter', models.IntegerField(null=True, verbose_name='Page Counter')),
            ],
        ),
    ]
