# Generated by Django 4.0.3 on 2022-03-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0145_pagecounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecounter',
            old_name='PageCounter',
            new_name='count',
        ),
    ]
