# Generated by Django 4.0.3 on 2022-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0146_rename_pagecounter_pagecounter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyprogressmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Commenced', 'Not Commenced')], default='Not Commenced', max_length=20, null=True),
        ),
    ]
