# Generated by Django 4.0.3 on 2022-03-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0149_ulbdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencybankdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agencyprogressmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agencysanctionmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ulbdetails',
            name='administrative_district',
        ),
        migrations.RemoveField(
            model_name='ulbdetails',
            name='ulbtype',
        ),
        migrations.RemoveField(
            model_name='ulbpancard',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DistrictWiseReport',
        ),
        migrations.DeleteModel(
            name='ProjectProgressDetailsReport',
        ),
        migrations.DeleteModel(
            name='ULBProgressIncompleted',
        ),
        migrations.DeleteModel(
            name='AgencyBankDetails',
        ),
        migrations.DeleteModel(
            name='AgencyProgressModel',
        ),
        migrations.DeleteModel(
            name='AgencySanctionModel',
        ),
        migrations.DeleteModel(
            name='ULBDetails',
        ),
        migrations.DeleteModel(
            name='ULBPanCard',
        ),
    ]
