# Generated by Django 4.0.3 on 2022-03-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0150_remove_agencybankdetails_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
