# Generated by Django 4.0.3 on 2022-04-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0153_alter_fundreleasedetails_options_releaserequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Bank'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='bank_name_ulb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the ULB'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release1Amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Release Amount 1'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release1Date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date 1'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release2Amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Release Amount 2'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release2Date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date 2'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release3Amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Release Amount 3'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release3Date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date 3'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release4Amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Release Amount 4'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release4Date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date 4'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release5Amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Release Amount 5'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='release5Date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date 5'),
        ),
    ]
