# Generated by Django 4.0.3 on 2022-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0154_alter_releaserequestmodel_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releaserequestmodel',
            options={'verbose_name': 'Fund Release Request', 'verbose_name_plural': 'Fund Release Requests'},
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='sqm_report2',
            field=models.FileField(blank=True, null=True, upload_to='SQMreport/', verbose_name='Instruction Report by SQM'),
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='sqm_report3',
            field=models.FileField(blank=True, null=True, upload_to='SQMreport/', verbose_name='Instruction Report by SQM'),
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='sqm_report4',
            field=models.FileField(blank=True, null=True, upload_to='SQMreport/', verbose_name='Instruction Report by SQM'),
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='sqm_report5',
            field=models.FileField(blank=True, null=True, upload_to='SQMreport/', verbose_name='Instruction Report by SQM'),
        ),
    ]
