# Generated by Django 4.0.3 on 2022-04-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0155_alter_releaserequestmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='ULBName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname'),
        ),
        migrations.AlterField(
            model_name='releaserequestmodel',
            name='ULBType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype'),
        ),
    ]
