# Generated by Django 4.0.4 on 2022-04-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0156_alter_releaserequestmodel_ulbname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPMasterSanctionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField(null=True, verbose_name='S No.')),
                ('Project_ID', models.CharField(max_length=10, null=True, verbose_name='Project ID')),
                ('ProjectCost', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Project Cost')),
                ('SchemeShare', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Scheme Share')),
                ('R1_Date', models.DateField(null=True, verbose_name='Date of 1st Release')),
                ('R1_Amount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Amount')),
                ('R2_Date', models.DateField(null=True, verbose_name='Date of 2nd Release')),
                ('R2_Amount', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Amount')),
                ('R_Total', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total Released')),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Balance')),
                ('Dropped', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Dropped Amount')),
                ('BalanceEligible', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Eligible for loan')),
                ('AgencyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname', verbose_name='ULB Name')),
                ('AgencyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype', verbose_name='ULB Type')),
                ('Scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme')),
            ],
            options={
                'verbose_name': 'SRP Master Sanction Form',
                'verbose_name_plural': 'SRP Master Sanction Form',
            },
        ),
    ]
