# Generated by Django 4.0.4 on 2022-04-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0157_srpmastersanctionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='BalanceEligible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eligible for loan'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R1_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R1_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of 1st Release'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R2_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R2_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of 2nd Release'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R_Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Released'),
        ),
    ]
