# Generated by Django 4.0.4 on 2022-04-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0158_alter_srpmastersanctionform_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srpmastersanctionform',
            name='Scheme',
        ),
    ]
