# Generated by Django 4.0.4 on 2022-04-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0160_alter_srpmastersanctionform_dropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='Balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='BalanceEligible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Eligible for loan'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='Dropped',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dropped Amount'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='ProjectCost',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Project Cost'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R1_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R2_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='R_Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Released'),
        ),
        migrations.AlterField(
            model_name='srpmastersanctionform',
            name='SchemeShare',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Scheme Share'),
        ),
    ]
