# Generated by Django 4.0.4 on 2022-04-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0161_alter_srpmastersanctionform_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_ref', models.CharField(max_length=30, null=True, verbose_name='GO ref.')),
                ('go_date', models.DateField(null=True, verbose_name='GO Date')),
                ('purpose', models.TextField(help_text='Scheme/Management Fee', null=True, verbose_name='Purpose')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Amount')),
                ('Scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.scheme')),
            ],
            options={
                'verbose_name': 'Receipt Form',
                'verbose_name_plural': 'Receipt Form',
            },
        ),
    ]
