# Generated by Django 4.0.4 on 2022-04-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0162_receiptform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaserequestmodel',
            name='ULBName',
        ),
        migrations.RemoveField(
            model_name='releaserequestmodel',
            name='ULBType',
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='AgencyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencyname', verbose_name='ULB Name'),
        ),
        migrations.AddField(
            model_name='releaserequestmodel',
            name='AgencyType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TUFIDCOapp.agencytype', verbose_name='ULB Type'),
        ),
    ]
