# Generated by Django 4.0.4 on 2022-04-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0163_remove_releaserequestmodel_ulbname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='releaserequestmodel',
            options={'verbose_name': 'Ledger: Release to ULBs', 'verbose_name_plural': 'Ledger: Release to ULBs'},
        ),
    ]
