# Generated by Django 4.0.4 on 2022-04-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0164_alter_releaserequestmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseRequestModel',
        ),
    ]
