# Generated by Django 4.0.4 on 2022-04-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0166_releaserequestmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterReport',
        ),
    ]
