# Generated by Django 4.0.4 on 2022-04-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0167_delete_masterreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseRequestModel',
        ),
    ]
