# Generated by Django 4.0.4 on 2022-05-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0168_delete_releaserequestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='scrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Scroll Message',
                'verbose_name_plural': 'Scroll Messages',
            },
        ),
    ]
