# Generated by Django 4.0.4 on 2022-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0169_scrollmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
    ]
