# Generated by Django 4.0.4 on 2022-05-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0171_remove_fundreleasedetails_mastersanctionform_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiptForm',
        ),
    ]
