# Generated by Django 4.0.3 on 2022-03-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TUFIDCOapp', '0150_remove_agencybankdetails_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
