# Generated by Django 4.0.4 on 2022-05-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('Dashboard', '0002_dashboardsingara_alter_dashboard_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardSingara',
        ),
        migrations.CreateModel(
            name='KNMTDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'KNMT',
                'verbose_name_plural': 'KNMT',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.CreateModel(
            name='SingaraChennaiDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Singara Chennai 2.0',
                'verbose_name_plural': 'Singara Chennai 2.0',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
