# Generated by Django 4.0.3 on 2022-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownPanchayatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField(null=True, verbose_name='S.No')),
                ('name_tp', models.CharField(max_length=40, null=True, verbose_name='Name of Town Panchayat')),
                ('district', models.CharField(max_length=40, null=True, verbose_name='District')),
                ('zone', models.CharField(max_length=40, null=True, verbose_name='Zone')),
                ('cell1', models.CharField(max_length=20, null=True, verbose_name='Cell 1')),
                ('cell2', models.CharField(max_length=20, null=True, verbose_name='Cell 2')),
                ('cell3', models.CharField(max_length=20, null=True, verbose_name='Cell 3')),
                ('email', models.EmailField(max_length=40, null=True, verbose_name='Email ID')),
            ],
        ),
    ]
