# Generated by Django 4.0.3 on 2022-03-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTP', '0002_townpanchayatdetails_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townpanchayatdetails',
            options={'verbose_name': 'Town Panchayat Detail', 'verbose_name_plural': 'Town Panchayat Details'},
        ),
        migrations.RemoveField(
            model_name='townpanchayatdetails',
            name='Sno',
        ),
    ]
