# Generated by Django 4.0.3 on 2022-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTP', '0003_alter_townpanchayatdetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townpanchayatdetails',
            name='cell2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell 2'),
        ),
        migrations.AlterField(
            model_name='townpanchayatdetails',
            name='cell3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cell 3'),
        ),
    ]
