# Generated by Django 4.0.3 on 2022-03-27 11:17

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('CTP', '0004_alter_townpanchayatdetails_cell2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='townpanchayatdetails',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
