# Generated by Django 4.0.3 on 2022-03-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0151_delete_location'),
        ('CTP', '0005_townpanchayatdetails_date_and_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterReport',
            fields=[
            ],
            options={
                'verbose_name': 'KNMT Physical & Financial Progress Report',
                'verbose_name_plural': 'KNMT Physical & Financial Progress Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
