# Generated by Django 4.0.4 on 2022-04-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTP', '0006_masterreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townpanchayatdetails',
            name='cell1',
            field=models.CharField(max_length=20, null=True, verbose_name='Executive officer ( Cell No 1)'),
        ),
        migrations.AlterField(
            model_name='townpanchayatdetails',
            name='cell2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Engineer Official Level 1 / AE ( Cell No 2)'),
        ),
        migrations.AlterField(
            model_name='townpanchayatdetails',
            name='cell3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Engineer Official Level 2 / JE ( Cell No 3)'),
        ),
    ]
