# Generated by Django 4.0.3 on 2022-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0003_alter_municipalitydetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalitydetails',
            name='mc',
            field=models.CharField(max_length=20, null=True, verbose_name='Municipal Commissioner Phone Number'),
        ),
        migrations.AlterField(
            model_name='municipalitydetails',
            name='me',
            field=models.CharField(max_length=20, null=True, verbose_name='Municipal Engineer Phone Number'),
        ),
    ]
