# Generated by Django 4.0.3 on 2022-03-27 11:20

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0004_alter_municipalitydetails_mc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalitydetails',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now, null=True),
        ),
    ]
