# Generated by Django 4.0.4 on 2022-05-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMA', '0006_masterreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='districtwisereport',
            options={'verbose_name': 'District Wise Report', 'verbose_name_plural': 'District Wise Report'},
        ),
    ]
