# Generated by Django 4.0.3 on 2022-03-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ULBProgressReport',
        ),
    ]
