# Generated by Django 4.0.3 on 2022-03-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ULBForms', '0017_delete_ulbprogressincompleted_and_more'),
        ('reports', '0002_delete_ulbprogressreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULBProgressIncompleted',
            fields=[
            ],
            options={
                'verbose_name': 'Portal Progress Detail',
                'verbose_name_plural': 'Portal Progress Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencyprogressmodel',),
        ),
        migrations.CreateModel(
            name='ULBSanctionReportError',
            fields=[
            ],
            options={
                'verbose_name': 'Portal Sanction Detail',
                'verbose_name_plural': 'Portal Sanction Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencysanctionmodel',),
        ),
    ]
