# Generated by Django 4.0.3 on 2022-03-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0151_delete_location'),
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'Progress Not Entered',
                'verbose_name_plural': 'Progress Not Entered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
