# Generated by Django 4.0.4 on 2022-04-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0161_alter_srpmastersanctionform_balance_and_more'),
        ('reports', '0005_sanctionnotentered_alter_progressnotentered_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRPAbstract',
            fields=[
            ],
            options={
                'verbose_name': 'SRP Abstract',
                'verbose_name_plural': 'SRP Abstract',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.srpmastersanctionform',),
        ),
    ]
