# Generated by Django 4.0.4 on 2022-04-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0162_receiptform'),
        ('reports', '0006_srpabstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Release Report',
                'verbose_name_plural': 'Release Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.releaserequestmodel',),
        ),
    ]
