# Generated by Django 4.0.4 on 2022-04-20 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_releasereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReleaseReport',
        ),
    ]
