# Generated by Django 4.0.4 on 2022-04-20 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0166_releaserequestmodel'),
        ('reports', '0008_delete_releasereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseReport',
            fields=[
            ],
            options={
                'verbose_name': 'Release Report',
                'verbose_name_plural': 'Release Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.releaserequestmodel',),
        ),
    ]
