# Generated by Django 4.0.4 on 2022-04-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0166_releaserequestmodel'),
        ('reports', '0009_releasereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalandFinancialReport',
            fields=[
            ],
            options={
                'verbose_name': 'KNMT Physical & Financial Progress Report',
                'verbose_name_plural': 'KNMT Physical & Financial Progress Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
