# Generated by Django 4.0.4 on 2022-05-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_delete_releasereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressNotEntered',
        ),
        migrations.DeleteModel(
            name='SanctionNotEntered',
        ),
        migrations.DeleteModel(
            name='ULBProgressIncompleted',
        ),
        migrations.DeleteModel(
            name='ULBSanctionReportError',
        ),
    ]
