# Generated by Django 4.0.4 on 2022-05-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULBForms', '0045_alter_agencyprogressmodel_approvedprojectcost'),
        ('reports', '0013_report_sectormasterreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNotCommenced',
            fields=[
            ],
            options={
                'verbose_name': 'Progress Not Commenced',
                'verbose_name_plural': 'Progress Not Commenced',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencyprogressmodel',),
        ),
    ]
