# Generated by Django 4.0.4 on 2022-05-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('reports', '0014_progressnotcommenced'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictWiseReport',
            fields=[
            ],
            options={
                'verbose_name': 'District Wise Report',
                'verbose_name_plural': 'District Wise Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
