# Generated by Django 4.0.4 on 2022-05-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0173_remove_agencyname_pid_remove_district_pid'),
        ('reports', '0015_districtwisereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingaraChennaiPhysicalandFinancialReport',
            fields=[
            ],
            options={
                'verbose_name': 'Singara Chennai Physical & Financial Progress Report',
                'verbose_name_plural': 'Singara Chennai Physical & Financial Progress Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
