# Generated by Django 4.0.4 on 2022-05-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_singarachennaiphysicalandfinancialreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singarachennaiphysicalandfinancialreport',
            options={'verbose_name': 'Singara Chennai 2.0 Physical & Financial Progress Report', 'verbose_name_plural': 'Singara Chennai 2.0 Physical & Financial Progress Report'},
        ),
    ]
