# Generated by Django 4.0.4 on 2022-05-26 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_singarachennaiphysicalandfinancialreport_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgressNotCommenced',
        ),
    ]
