# Generated by Django 4.0 on 2022-01-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0083_agencysanctionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysanctionmodel',
            name='agencysanction/',
        ),
        migrations.RemoveField(
            model_name='agencysanctionmodel',
            name='agencysanctionlocation/',
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='upload1',
            field=models.FileField(help_text='Please upload a photo of site with location matching with the google maps', null=True, upload_to='agencysanctionlocation/', verbose_name='upload'),
        ),
        migrations.AddField(
            model_name='agencysanctionmodel',
            name='upload2',
            field=models.FileField(blank=True, null=True, upload_to='agencysanction/', verbose_name='upload'),
        ),
    ]
