# Generated by Django 4.0.4 on 2022-05-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ULBForms', '0046_alter_agencyprogressmodel_nc_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityCompletedProjects',
            fields=[
            ],
            options={
                'verbose_name': 'DMA Completed Projects',
                'verbose_name_plural': 'DMA Completed Projects',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ULBForms.agencyprogressmodel',),
        ),
    ]
